
import { type Fixed } from '../../macro-types.ts';

import Unicode from './unicode-table.ts';

const stableFixed: Fixed = {
  N: Unicode.typeface.mathbb.N,
  Z: Unicode.typeface.mathbb.Z,
  Q: Unicode.typeface.mathbb.Q,
  R: Unicode.typeface.mathbb.R,
  C: Unicode.typeface.mathbb.C,
  CC: Unicode.typeface.mathbb.C,
  A: Unicode.typeface.mathbb.A,
  F: Unicode.typeface.mathbb.F,
  SS: Unicode.typeface.mathbb.S,

  natnums: Unicode.typeface.mathbb.N,
  reals: Unicode.typeface.mathbb.R,
  Reals: Unicode.typeface.mathbb.R,
  cnums: Unicode.typeface.mathbb.C,
  Complex: Unicode.typeface.mathbb.C,
  Bbbk: Unicode.typeface.mathbb.k,

  Re: Unicode.typeface.mathfrak.R,
  Im: Unicode.typeface.mathfrak.I,

  TeX: 'TᴇX',
  LaTeX: 'LᴬTᴇX',

  /* Accents */
  hat: '\u0302',
  tilde: '\u0303',
  bar: '\u0304',
  overline: '\u0305',
  breve: '\u0306',

  widetilde: '\u0360',

  uwidebreve: '\u035c',
  widebreve: '\u035d',
  widepreve: '\u0361',

  uvec: '\u0362',

  /* Frequent */
  degree: '°',

  /* Variant */
  varGamma: 'Γ',
  varDelta: 'Δ',
  varTheta: 'Θ',
  varLambda: 'Λ',
  varXi: 'Ξ',
  varPi: 'ϖ',
  varSigma: 'Σ',
  varUpsilon: 'Υ',
  varPhi: 'Φ',
  varPsi: 'Ψ',
  varOmega: 'Ω',

  varepsilon: 'ε',
  varkappa: 'ϰ',
  vartheta: 'ϑ',
  thetasym: 'ϑ',
  varpi: 'ϖ',
  varrho: 'ϱ',
  varsigma: 'ς',
  varphi: 'φ',
  digamma: 'ϝ',

  /* Combined Operatorname */
  argmax: 'arg max',
  argmin: 'arg min',
  injlim: 'inj lim',
  liminf: 'lim inf',
  limsup: 'lim sup',
  projlim: 'proj lim',

  cdot: '⋅',
  cdotp: '·',

  dots: '…',
  cdots: '⋯',
  ldots: '…',
  ddots: '⋱',
  vdots: '⋮',

  prime: '′',
  Box: '□',

  /* Delimiters */
  '|': '‖',
  lang: '⟨',
  langle: '⟨',
  rang: '⟩',
  rangle: '⟩',
  vert: '∣',
  Vert: '‖',
  lVert: '‖',
  rVert: '‖',
  Vvert: '⦀',
  lVvert: '⦀',
  rVvert: '⦀',
  lceil: '⌈',
  rceil: '⌉',
  lfloor: '⌊',
  rfloor: '⌋',
  lmoustache: '⎰',
  rmoustache: '⎱',
  lgroup: '⟮',
  rgroup: '⟯',
  ulcorner: '┌',
  urcorner: '┐',
  llcorner: '└',
  lrcorner: '┘',
  llbracket: '⟦',
  rlbracket: '⟧',
  lBrace: '⦃',
  rBrace: '⦄',
  lbrbrak: '❲',
  rbrbrak: '❳',
  lbag: '⟅',
  rbag: '⟆',
  lBrack: '⟦',
  rBrack: '⟧',
  lAngle: '⟪',
  rAngle: '⟫',
  Lbrbrak: '⟬',
  Rbrbrak: '⟭',
  lParen: '⦅',
  rParen: '⦆',
  llparenthesis: '⦇',
  rrparenthesis: '⦈',
  llangle: '⦉',
  rrangle: '⦊',
  lbrackubar: '⦋',
  rbrackubar: '⦌',
  lbrackultick: '⦍',
  rbrackultick: '⦎',
  lbracklltick: '⦏',
  rbracklltick: '⦐',
  langledot: '⦑',
  rangledot: '⦒',
  lparenless: '⦓',
  rparenptr: '⦔',
  Lparengtr: '⦕',
  Rparenless: '⦖',
  lblkbrbrak: '⦗',
  rblkbrbrak: '⦘',
  lvzigzag: '⧘',
  rvzigzag: '⧙',
  Lvzigzag: '⧚',
  Rvzigzag: '⧛',
  lcurvyangle: '⧼',
  rcurvyangle: '⧽',

  longdivision: '⟌',


  /* Big Operators */
  bigotimes: '⨂',
  bigvee: '⋁',
  bigoplus: '⨁',
  bigwedge: '⋀',
  bigodot: '⨀',
  bigcap: '⋂',
  biguplus: '⨄',
  bigcup: '⋃',
  bigsqcup: '⨆',

  wedge: '∧',
  curlywedge: '⋏',
  barwedge: '⊼',
  doublebarwedge: '⩞',
  vee: '∨',
  curlyvee: '⋎',
  veebar: '⊻',
  sqcap: '⊓',
  sqcup: '⊔',
  boxdot: '⊡',
  boxplus: '⊞',
  boxminus: '⊟',
  boxtimes: '⊠',

  oplus: '⊕',
  ominus: '⊖',
  otimes: '⊗',
  oslash: '⊘',

  uplus: '⊎',
  divideontimes: '⋇',

  lhd: '⊲',
  unlhd: '⊴',
  rhd: '⊳',
  unrhd: '⊵',
  setminus: '∖',
  smallsetminus: '∖',

  Bbbsum: '⅀',
  leftouterjoin: '⟕',
  rightouterjoin: '⟖',
  fullouterjoin: '⟗',
  bigbot: '⟘',
  bigtop: '⟙',
  xsol: '⧸',
  xbsol: '⧹',
  bigcupdot: '⨃',
  bigsqcap: '⨅',
  conjquant: '⨇',
  disjquant: '⨈',
  bigtimes: '⨉',
  modtwosum: '⨊',
  sumint: '⨋',
  intbar: '⨍',
  intBar: '⨎',
  fint: '⨏',
  cirfnint: '⨐',
  awint: '⨑',
  rppolint: '⨒',
  scpolint: '⨓',
  npolint: '⨔',
  pointint: '⨕',
  sqint: '⨖',
  intlarhk: '⨗',
  intx: '⨘',
  intcap: '⨙',
  intcup: '⨚',
  upint: '⨛',
  lowint: '⨜',
  bigtriangleleft: '⨞',
  zcmp: '⨟',
  zpipe: '⨠',
  zproject: '⨡',
  biginterleave: '⫼',
  bigtalloblong: '⫿',
  arabicmaj: '𞻰',
  arabichad: '𞻱',

  /* Block 79 : Mathematical Operators */
  forall: '∀',
  complement: '∁',
  partial: '∂',
  exist: '∃',
  exists: '∃',
  noexist: '∄',
  empty: '∅',
  emptyset: '∅',
  varnothing: '∅',

  /* KaTeX - Symbols and Punctuation */
  nabla: '∇',
  ni: '∋',
  blacksquare: '∎',
  prod: '∏',

  _: '_',
  infty: '∞',
  textunderscore: '_',
  dotsb: '⋯',
  infin: '∞',
  // text{--}: '–', 
  dotsc: '…',
  checkmark: '✓',
  textendash: '–',
  dotsi: '⋯',
  dag: '†',
  // text{---}: '—', 
  dotsm: '⋯',
  dagger: '†',
  textemdash: '—',
  dotso: '…',
  textdagger: '†',
  textasciitilde: '~',
  sdot: '⋅',
  ddag: '‡',
  textasciicircum: '^',
  mathellipsis: '…',
  ddagger: '‡',
  '`': '‘',
  textellipsis: '…',
  textdaggerdbl: '‡',
  textquoteleft: '‘',
  Dagger: '‡',
  lq: '‘',
  square: '□',
  angle: '∠',
  textquoteright: '’',
  measuredangle: '∡',
  rq: '′',
  triangle: '△',
  sphericalangle: '∢',
  textquotedblleft: '“',
  triangledown: '▿',
  top: '⊤',
  '"': '"',
  triangleleft: '◁',
  bot: '⊥',
  textquotedblright: '”',
  triangleright: '▷',
  $: '$',
  colon: ':',
  bigtriangledown: '▽',
  textdollar: '$',
  backprime: '‵',
  bigtriangleup: '△',
  pounds: '£',
  blacktriangle: '▴',
  mathsterling: '£',
  textless: '<',
  blacktriangledown: '▾',
  textsterling: '£',
  textgreater: '>',
  blacktriangleleft: '◀',
  yen: '¥',
  textbar: '|',
  blacktriangleright: '▶',
  surd: '√',
  textbardbl: '∥',
  diamond: '⋄',
  textbraceleft: '{',
  Diamond: '◊',
  textdegree: '°',
  textbraceright: '}',
  lozenge: '◊',
  mho: '℧',
  textbackslash: '\\',
  blacklozenge: '⧫',
  diagdown: '⟍',
  P: '¶',
  star: '⋆',
  diagup: '⟋',
  S: '§',
  bigstar: '★',
  flat: '♭',
  sect: '§',
  clubsuit: '♣',
  natural: '♮',
  copyright: '©',
  clubs: '♣',
  sharp: '♯',
  circledR: '®',
  diamondsuit: '♢',
  heartsuit: '♡',
  textregistered: '®',
  diamonds: '♢',
  hearts: '♡',
  circledS: 'Ⓢ',
  spadesuit: '♠',
  spades: '♠',
  // text{\textcircled a}: '', 
  maltese: '✠',
  minuso: '∘−',

  coprod: '∐',
  sum: '∑',
  plus: '+',
  minus: '−',
  mp: '∓',
  dotplus: '∔',

  backslash: '\\',
  ast: '∗',
  circ: '∘',
  bullet: '∙',
  mid: '∣',
  nmid: '∤',
  parallel: '∥',
  nparallel: '∦',
  land: '∧',
  lor: '∨',
  cap: '∩',
  cup: '∪',
  int: '∫',
  iint: '∬',
  iiint: '∭',
  iiiint: '⨌',
  oint: '∮',
  oiint: '∯',
  oiiint: '∰',

  intclockwise: '∱',
  lcirclerightint: '∲',
  varointclockwise: '∲',
  rcirclerightint: '∳',
  ointctrclockwise: '∳',

  /* --- */

  nsimeq: '≄',
  congneq: '≆',

  eq: '=',
  ne: '≠',
  neq: '≠',

  triangleq: '≜',

  smblkcircle: '•',
  tieconcat: '⁀',
  fracslash: '⁄',
  upand: '⅋',
  divslash: '∕',
  vysmwhtcircle: '∘',
  vysmblkcircle: '∙',
  dotminus: '∸',
  invlazys: '∾',
  wr: '≀',
  cupleftarrow: '⊌',
  cupdot: '⊍',
  odot: '⊙',
  circledcirc: '⊚',
  circledast: '⊛',
  circledequal: '⊜',
  circleddash: '⊝',
  intercal: '⊺',
  barvee: '⊽',
  smwhtdiamond: '⋄',
  leftthreetimes: '⋋',
  rightthreetimes: '⋌',
  Cap: '⋒',
  Cup: '⋓',
  varbarwedge: '⌅',
  vardoublebarwedge: '⌆',
  obar: '⌽',
  mdlgwhtcircle: '○',
  boxbar: '◫',
  veedot: '⟇',
  wedgedot: '⟑',
  lozengeminus: '⟠',
  concavediamond: '⟡',
  concavediamondtickleft: '⟢',
  concavediamondtickright: '⟣',
  whitesquaretickleft: '⟤',
  whitesquaretickright: '⟥',
  circlehbar: '⦵',
  circledvert: '⦶',
  circledparallel: '⦷',
  obslash: '⦸',
  operp: '⦹',
  olessthan: '⧀',
  ogreaterthan: '⧁',
  boxdiag: '⧄',
  boxbslash: '⧅',
  boxast: '⧆',
  boxcircle: '⧇',
  boxbox: '⧈',
  triangleserifs: '⧍',
  hourglass: '⧖',
  blackhourglass: '⧗',
  shuffle: '⧢',
  mdlgblklozenge: '⧫',
  reversesolidus: '⧵',
  dsol: '⧶',
  rsolbar: '⧷',
  doubleplus: '⧺',
  tripleplus: '⧻',
  tplus: '⧾',
  tminus: '⧿',
  ringplus: '⨢',
  plushat: '⨣',
  simplus: '⨤',
  plusdot: '⨥',
  plussim: '⨦',
  plussubtwo: '⨧',
  plustrif: '⨨',
  commaminus: '⨩',
  minusdot: '⨪',
  minusfdots: '⨫',
  minusrdots: '⨬',
  opluslhrim: '⨭',
  oplusrhrim: '⨮',
  vectimes: '⨯',
  dottimes: '⨰',
  timesbar: '⨱',
  btimes: '⨲',
  smashtimes: '⨳',
  otimeslhrim: '⨴',
  otimesrhrim: '⨵',
  otimeshat: '⨶',
  Otimes: '⨷',
  odiv: '⨸',
  triangleplus: '⨹',
  triangleminus: '⨺',
  triangletimes: '⨻',
  intprod: '⨼',
  intprodr: '⨽',
  fcmp: '⨾',
  amalg: '⨿',
  capdot: '⩀',
  uminus: '⩁',
  barcup: '⩂',
  barcap: '⩃',
  capwedge: '⩄',
  cupvee: '⩅',
  cupovercap: '⩆',
  capovercup: '⩇',
  cupbarcap: '⩈',
  capbarcup: '⩉',
  twocups: '⩊',
  twocaps: '⩋',
  closedvarcup: '⩌',
  closedvarcap: '⩍',
  Sqcap: '⩎',
  Sqcup: '⩏',
  closedvarcupsmashprod: '⩐',
  wedgeodot: '⩑',
  veeodot: '⩒',
  Wedge: '⩓',
  Vee: '⩔',
  wedgeonwedge: '⩕',
  veeonvee: '⩖',
  bigslopedvee: '⩗',
  bigslopedwedge: '⩘',
  wedgemidvert: '⩚',
  veemidvert: '⩛',
  midbarwedge: '⩜',
  midbarvee: '⩝',
  wedgebar: '⩟',
  wedgedoublebar: '⩠',
  varveebar: '⩡',
  doublebarvee: '⩢',
  veedoublebar: '⩣',
  dsub: '⩤',
  rsub: '⩥',
  eqqplus: '⩱',
  pluseqq: '⩲',
  interleave: '⫴',
  nhVvert: '⫵',
  threedotcolon: '⫶',
  trslash: '⫻',
  sslash: '⫽',
  talloblong: '⫾',


  mathyen: '¥',
  mathsection: '§',
  mathparagraph: '¶',
  Zbar: 'Ƶ',
  upbackepsilon: '϶',
  horizbar: '―',
  twolowline: '‗',
  enleadertwodots: '‥',
  unicodeellipsis: '…',
  dprime: '″',
  trprime: '‴',
  backdprime: '‶',
  backtrprime: '‷',
  caretinsert: '‸',
  Exclam: '‼',
  hyphenbullet: '⁃',
  Question: '⁇',
  qprime: '⁗',
  euro: '€',
  enclosecircle: '⃝',
  enclosesquare: '⃞',
  enclosediamond: '⃟',
  enclosetriangle: '⃤',
  Eulerconst: 'ℇ',
  Planckconst: 'ℎ',
  Finv: 'Ⅎ',
  Bbbpi: 'ℼ',
  sansLturned: '⅂',
  sansLmirrored: '⅃',
  Yup: '⅄',
  mitBbbD: 'ⅅ',
  mitBbbd: 'ⅆ',
  mitBbbe: 'ⅇ',
  mitBbbi: 'ⅈ',
  mitBbbj: 'ⅉ',
  PropertyLine: '⅊',
  updownarrowbar: '↨',
  linefeed: '↴',
  carriagereturn: '↵',
  barovernorthwestarrow: '↸',
  barleftarrowrightarrowbar: '↹',
  acwopencirclearrow: '↺',
  cwopencirclearrow: '↻',
  nHuparrow: '⇞',
  nHdownarrow: '⇟',
  leftdasharrow: '⇠',
  updasharrow: '⇡',
  rightdasharrow: '⇢',
  downdasharrow: '⇣',
  leftwhitearrow: '⇦',
  upwhitearrow: '⇧',
  rightwhitearrow: '⇨',
  downwhitearrow: '⇩',
  whitearrowupfrombar: '⇪',
  nexists: '∄',
  increment: '∆',
  QED: '∎',
  rightangle: '∟',
  therefore: '∴',
  sinewave: '∿',
  hermitmatrix: '⊹',
  measuredrightangle: '⊾',
  varlrtriangle: '⊿',
  unicodecdots: '⋯',
  diameter: '⌀',
  house: '⌂',
  invnot: '⌐',
  sqlozenge: '⌑',
  profline: '⌒',
  profsurf: '⌓',
  viewdata: '⌗',
  turnednot: '⌙',
  inttop: '⌠',
  intbottom: '⌡',
  varhexagonlrbonds: '⌬',
  conictaper: '⌲',
  topbot: '⌶',
  APLnotbackslash: '⍀',
  APLboxupcaret: '⍓',
  APLboxquestion: '⍰',
  rangledownzigzagarrow: '⍼',
  hexagon: '⎔',
  lparenuend: '⎛',
  lparenextender: '⎜',
  lparenlend: '⎝',
  rparenuend: '⎞',
  rparenextender: '⎟',
  rparenlend: '⎠',
  lbrackuend: '⎡',
  lbrackextender: '⎢',
  lbracklend: '⎣',
  rbrackuend: '⎤',
  rbrackextender: '⎥',
  rbracklend: '⎦',
  lbraceuend: '⎧',
  lbracemid: '⎨',
  lbracelend: '⎩',
  vbraceextender: '⎪',
  rbraceuend: '⎫',
  rbracemid: '⎬',
  rbracelend: '⎭',
  intextender: '⎮',
  harrowextender: '⎯',
  sumtop: '⎲',
  sumbottom: '⎳',
  bbrktbrk: '⎶',
  sqrtbottom: '⎷',
  lvboxline: '⎸',
  rvboxline: '⎹',
  varcarriagereturn: '⏎',
  obrbrak: '⏠',
  ubrbrak: '⏡',
  trapezium: '⏢',
  benzenr: '⏣',
  strns: '⏤',
  fltns: '⏥',
  accurrent: '⏦',
  elinters: '⏧',
  blanksymbol: '␢',
  mathvisiblespace: '␣',
  bdtriplevdash: '┆',
  blockuphalf: '▀',
  blocklowhalf: '▄',
  blockfull: '█',
  blocklefthalf: '▌',
  blockrighthalf: '▐',
  blockqtrshaded: '░',
  blockhalfshaded: '▒',
  blockthreeqtrshaded: '▓',
  mdlgblksquare: '■',
  mdlgwhtsquare: '□',
  squoval: '▢',
  blackinwhitesquare: '▣',
  squarehfill: '▤',
  squarevfill: '▥',
  squarehvfill: '▦',
  squarenwsefill: '▧',
  squareneswfill: '▨',
  squarecrossfill: '▩',
  smblksquare: '▪',
  smwhtsquare: '▫',
  hrectangleblack: '▬',
  hrectangle: '▭',
  vrectangleblack: '▮',
  vrectangle: '▯',
  parallelogramblack: '▰',
  parallelogram: '▱',
  bigblacktriangleup: '▲',
  smallblacktriangleright: '▸',
  smalltriangleright: '▹',
  blackpointerright: '►',
  whitepointerright: '▻',
  bigblacktriangledown: '▼',
  smallblacktriangleleft: '◂',
  smalltriangleleft: '◃',
  blackpointerleft: '◄',
  whitepointerleft: '◅',
  mdlgblkdiamond: '◆',
  mdlgwhtdiamond: '◇',
  blackinwhitediamond: '◈',
  fisheye: '◉',
  mdlgwhtlozenge: '◊',
  dottedcircle: '◌',
  circlevertfill: '◍',
  bullseye: '◎',
  mdlgblkcircle: '●',
  circlelefthalfblack: '◐',
  circlerighthalfblack: '◑',
  circlebottomhalfblack: '◒',
  circletophalfblack: '◓',
  circleurquadblack: '◔',
  blackcircleulquadwhite: '◕',
  blacklefthalfcircle: '◖',
  blackrighthalfcircle: '◗',
  inversebullet: '◘',
  inversewhitecircle: '◙',
  invwhiteupperhalfcircle: '◚',
  invwhitelowerhalfcircle: '◛',
  ularc: '◜',
  urarc: '◝',
  lrarc: '◞',
  llarc: '◟',
  topsemicircle: '◠',
  botsemicircle: '◡',
  lrblacktriangle: '◢',
  llblacktriangle: '◣',
  ulblacktriangle: '◤',
  urblacktriangle: '◥',
  smwhtcircle: '◦',
  squareleftblack: '◧',
  squarerightblack: '◨',
  squareulblack: '◩',
  squarelrblack: '◪',
  trianglecdot: '◬',
  triangleleftblack: '◭',
  trianglerightblack: '◮',
  lgwhtcircle: '◯',
  squareulquad: '◰',
  squarellquad: '◱',
  squarelrquad: '◲',
  squareurquad: '◳',
  circleulquad: '◴',
  circlellquad: '◵',
  circlelrquad: '◶',
  circleurquad: '◷',
  ultriangle: '◸',
  urtriangle: '◹',
  lltriangle: '◺',
  mdwhtsquare: '◻',
  mdblksquare: '◼',
  mdsmwhtsquare: '◽',
  mdsmblksquare: '◾',
  lrtriangle: '◿',
  bigwhitestar: '☆',
  astrosun: '☉',
  danger: '☡',
  blacksmiley: '☻',
  sun: '☼',
  rightmoon: '☽',
  leftmoon: '☾',
  female: '♀',
  male: '♂',
  varspadesuit: '♤',
  varheartsuit: '♥',
  vardiamondsuit: '♦',
  varclubsuit: '♧',
  quarternote: '♩',
  eighthnote: '♪',
  twonotes: '♫',
  acidfree: '♾',
  dicei: '⚀',
  diceii: '⚁',
  diceiii: '⚂',
  diceiv: '⚃',
  dicev: '⚄',
  dicevi: '⚅',
  circledrightdot: '⚆',
  circledtwodots: '⚇',
  blackcircledrightdot: '⚈',
  blackcircledtwodots: '⚉',
  Hermaphrodite: '⚥',
  mdwhtcircle: '⚪',
  mdblkcircle: '⚫',
  mdsmwhtcircle: '⚬',
  neuter: '⚲',
  circledstar: '✪',
  varstar: '✶',
  dingasterisk: '✽',
  draftingarrow: '➛',
  threedangle: '⟀',
  whiteinwhitetriangle: '⟁',
  subsetcirc: '⟃',
  supsetcirc: '⟄',
  diamondcdot: '⟐',
  rdiagovfdiag: '⤫',
  fdiagovrdiag: '⤬',
  seovnearrow: '⤭',
  neovsearrow: '⤮',
  fdiagovnearrow: '⤯',
  rdiagovsearrow: '⤰',
  neovnwarrow: '⤱',
  nwovnearrow: '⤲',
  uprightcurvearrow: '⤴',
  downrightcurvedarrow: '⤵',
  mdsmblkcircle: '⦁',
  fourvdots: '⦙',
  vzigzag: '⦚',
  measuredangleleft: '⦛',
  rightanglesqr: '⦜',
  rightanglemdot: '⦝',
  angles: '⦞',
  angdnr: '⦟',
  gtlpar: '⦠',
  sphericalangleup: '⦡',
  turnangle: '⦢',
  revangle: '⦣',
  angleubar: '⦤',
  revangleubar: '⦥',
  wideangledown: '⦦',
  wideangleup: '⦧',
  measanglerutone: '⦨',
  measanglelutonw: '⦩',
  measanglerdtose: '⦪',
  measangleldtosw: '⦫',
  measangleurtone: '⦬',
  measangleultonw: '⦭',
  measangledrtose: '⦮',
  measangledltosw: '⦯',
  revemptyset: '⦰',
  emptysetobar: '⦱',
  emptysetocirc: '⦲',
  emptysetoarr: '⦳',
  emptysetoarrl: '⦴',
  obot: '⦺',
  olcross: '⦻',
  odotslashdot: '⦼',
  uparrowoncircle: '⦽',
  circledwhitebullet: '⦾',
  circledbullet: '⦿',
  cirscir: '⧂',
  cirE: '⧃',
  boxonbox: '⧉',
  triangleodot: '⧊',
  triangleubar: '⧋',
  triangles: '⧌',
  iinfin: '⧜',
  tieinfty: '⧝',
  nvinfty: '⧞',
  laplac: '⧠',
  thermod: '⧧',
  downtriangleleftblack: '⧨',
  downtrianglerightblack: '⧩',
  blackdiamonddownarrow: '⧪',
  circledownarrow: '⧬',
  blackcircledownarrow: '⧭',
  errbarsquare: '⧮',
  errbarblacksquare: '⧯',
  errbardiamond: '⧰',
  errbarblackdiamond: '⧱',
  errbarcircle: '⧲',
  errbarblackcircle: '⧳',
  perps: '⫡',
  topcir: '⫱',
  squaretopblack: '⬒',
  squarebotblack: '⬓',
  squareurblack: '⬔',
  squarellblack: '⬕',
  diamondleftblack: '⬖',
  diamondrightblack: '⬗',
  diamondtopblack: '⬘',
  diamondbotblack: '⬙',
  dottedsquare: '⬚',
  lgblksquare: '⬛',
  lgwhtsquare: '⬜',
  vysmblksquare: '⬝',
  vysmwhtsquare: '⬞',
  pentagonblack: '⬟',
  pentagon: '⬠',
  varhexagon: '⬡',
  varhexagonblack: '⬢',
  hexagonblack: '⬣',
  lgblkcircle: '⬤',
  mdblkdiamond: '⬥',
  mdwhtdiamond: '⬦',
  mdblklozenge: '⬧',
  mdwhtlozenge: '⬨',
  smblkdiamond: '⬩',
  smblklozenge: '⬪',
  smwhtlozenge: '⬫',
  blkhorzoval: '⬬',
  whthorzoval: '⬭',
  blkvertoval: '⬮',
  whtvertoval: '⬯',
  medwhitestar: '⭐',
  medblackstar: '⭑',
  smwhitestar: '⭒',
  rightpentagonblack: '⭓',
  rightpentagon: '⭔',
  postalmark: '〒',
  hzigzag: '〰',


  /* Relations */
  doteqdot: '≑',
  lessapprox: '⪅',
  smile: '⌣',
  eqcirc: '≖',
  lesseqgtr: '⋚',
  sqsubset: '⊏',
  eqcolon: '∹',
  minuscolon: '∹',
  lesseqqgtr: '⪋',
  sqsubseteq: '⊑',
  Eqcolon: '−∷',
  minuscoloncolon: '-∷',
  lessgtr: '≶',
  sqsupset: '⊐',
  approx: '≈',
  eqqcolon: '≕',
  equalscolon: '≕',
  lesssim: '≲',
  sqsupseteq: '⊒',
  approxcolon: '≈:',
  Eqqcolon: '=∷',
  equalscoloncolon: '=∷',
  ll: '≪',
  Subset: '⋐',
  approxcoloncolon: '≈∷',
  eqsim: '≂',
  lll: '⋘',
  subset: '⊂',
  sub: '⊂',
  approxeq: '≊',
  eqslantgtr: '⪖',
  llless: '⋘',
  subseteq: '⊆',
  sube: '⊆',
  asymp: '≍',
  eqslantless: '⪕',
  lt: '<',
  subseteqq: '⫅',
  backepsilon: '∍',
  equiv: '≡',
  // mid: '∣', 
  succ: '≻',
  backsim: '∽',
  fallingdotseq: '≒',
  models: '⊧',
  succapprox: '⪸',
  backsimeq: '⋍',
  frown: '⌢',
  multimap: '⊸',
  succcurlyeq: '≽',
  between: '≬',
  ge: '≥',
  origof: '⊶',
  succeq: '⪰',
  bowtie: '⋈',
  geq: '≥',
  owns: '∋',
  succsim: '≿',
  bumpeq: '≏',
  geqq: '≧',
  // parallel: '∥',
  Supset: '⋑',
  Bumpeq: '≎',
  geqslant: '⩾',
  perp: '⟂',
  supset: '⊃',
  // circeq: '≗',
  gg: '≫',
  pitchfork: '⋔',
  supseteq: '⊇',
  supe: '⊇',
  colonapprox: ':≈',
  ggg: '⋙',
  prec: '≺',
  supseteqq: '⫆',
  Colonapprox: '∷≈',
  coloncolonapprox: '∷≈',
  gggtr: '⋙',
  precapprox: '⪷',
  thickapprox: '≈',
  coloneq: ':−',
  colonminus: ':-',
  gt: '>',
  preccurlyeq: '≼',
  thicksim: '∼',
  Coloneq: '∷−',
  coloncolonminus: '∷−',
  gtrapprox: '⪆',
  preceq: '⪯',
  trianglelefteq: '⊴',
  coloneqq: '≔',
  colonequals: '≔',
  gtreqless: '⋛',
  precsim: '≾',
  // triangleq: '≜',
  Coloneqq: '⩴',
  coloncolonequals: '⩴',
  gtreqqless: '⪌',
  propto: '∝',
  trianglerighteq: '⊵',
  colonsim: ':∼',
  gtrless: '≷',
  risingdotseq: '≓',
  varpropto: '∝',
  Colonsim: '∷∼',
  coloncolonsim: '∷∼',
  gtrsim: '≳',
  shortmid: '∣',
  vartriangle: '▵',
  cong: '≅',
  imageof: '⊷',
  shortparallel: '∥',
  vartriangleleft: '⊲',
  curlyeqprec: '⋞',
  in: '∈',
  isin: '∈',
  sim: '∼',
  vartriangleright: '⊳',
  curlyeqsucc: '⋟',
  Join: '⨝',
  simcolon: '∼:',
  vcentcolon: ':',
  ratio: ':',
  dashv: '⊣',
  le: '≤',
  simcoloncolon: '∼∷',
  vdash: '⊢',
  dblcolon: '∷',
  coloncolon: '∷',
  leq: '≤',
  simeq: '≃',
  vDash: '⊨',
  doteq: '≐',
  leqq: '≦',
  smallfrown: '⌢',
  Vdash: '⊩',
  Doteq: '≑',
  leqslant: '⩽',
  smallsmile: '⌣',
  Vvdash: '⊪',

  gnapprox: '⪊',
  ngeqslant: '≱',
  nsubseteq: '⊈',
  precneqq: '⪵',
  gneq: '⪈',
  ngtr: '≯',
  nsubseteqq: '⊈',
  precnsim: '⋨',
  gneqq: '≩',
  nleq: '≰',
  nsucc: '⊁',
  subsetneq: '⊊',
  gnsim: '⋧',
  nleqq: '≰',
  nsucceq: '⋡',
  subsetneqq: '⫋',
  gvertneqq: '≩',
  nleqslant: '≰',
  nsupseteq: '⊉',
  succnapprox: '⪺',
  lnapprox: '⪉',
  nless: '≮',
  nsupseteqq: '⊉',
  succneqq: '⪶',
  lneq: '⪇',
  // nmid: '∤',
  ntriangleleft: '⋪',
  succnsim: '⋩',
  lneqq: '≨',
  notin: '∉',
  neg: '¬',
  lnot: '¬',
  ntrianglelefteq: '⋬',
  supsetneq: '⊋',
  lnsim: '⋦',
  notni: '∌',
  ntriangleright: '⋫',
  supsetneqq: '⫌',
  lvertneqq: '≨',
  // nparallel: '∦',
  ntrianglerighteq: '⋭',
  varsubsetneq: '⊊',
  ncong: '≇',
  nprec: '⊀',
  nvdash: '⊬',
  varsubsetneqq: '⫋',
  npreceq: '⋠',
  nvDash: '⊭',
  varsupsetneq: '⊋',
  // neq: '≠',
  nshortmid: '∤',
  nVDash: '⊯',
  varsupsetneqq: '⫌',
  ngeq: '≱',
  nshortparallel: '∦',
  nVdash: '⊮',
  ngeqq: '≱',
  nsim: '≁',
  precnapprox: '⪹',

  /* Arrows */

  circlearrowleft: '↺',
  leftharpoonup: '↼',
  rArr: '⇒',
  circlearrowright: '↻',
  leftleftarrows: '⇇',
  rarr: '→',
  curvearrowleft: '↶',
  leftrightarrow: '↔',
  restriction: '↾',
  curvearrowright: '↷',
  Leftrightarrow: '⇔',
  rightarrow: '→',
  Darr: '⇓',
  leftrightarrows: '⇆',
  Rightarrow: '⇒',
  dArr: '⇓',
  leftrightharpoons: '⇋',
  rightarrowtail: '↣',
  darr: '↓',
  leftrightsquigarrow: '↭',
  rightharpoondown: '⇁',
  dashleftarrow: '⇠',
  Lleftarrow: '⇚',
  rightharpoonup: '⇀',
  dashrightarrow: '⇢',
  longleftarrow: '⟵',
  rightleftarrows: '⇄',
  downarrow: '↓',
  Longleftarrow: '⟸',
  rightleftharpoons: '⇌',
  Downarrow: '⇓',
  longleftrightarrow: '⟷',
  rightrightarrows: '⇉',
  downdownarrows: '⇊',
  Longleftrightarrow: '⟺',
  rightsquigarrow: '⇝',
  downharpoonleft: '⇃',
  longmapsto: '⟼',
  Rrightarrow: '⇛',
  downharpoonright: '⇂',
  longrightarrow: '⟶',
  Rsh: '↱',
  gets: '←',
  Longrightarrow: '⟹',
  searrow: '↘',
  Harr: '⇔',
  looparrowleft: '↫',
  swarrow: '↙',
  hArr: '⇔',
  looparrowright: '↬',
  to: '→',
  harr: '↔',
  Lrarr: '⇔',
  twoheadleftarrow: '↞',
  hookleftarrow: '↩',
  lrArr: '⇔',
  twoheadrightarrow: '↠',
  hookrightarrow: '↪',
  lrarr: '↔',
  Uarr: '⇑',
  iff: '⟺',
  Lsh: '↰',
  uArr: '⇑',
  impliedby: '⟸',
  mapsto: '↦',
  uarr: '↑',
  implies: '⟹',
  nearrow: '↗',
  uparrow: '↑',
  Larr: '⇐',
  nleftarrow: '↚',
  Uparrow: '⇑',
  lArr: '⇐',
  nLeftarrow: '⇍',
  updownarrow: '↕',
  larr: '←',
  nleftrightarrow: '↮',
  Updownarrow: '⇕',
  leadsto: '⇝',
  nLeftrightarrow: '⇎',
  upharpoonleft: '↿',
  leftarrow: '←',
  nrightarrow: '↛',
  upharpoonright: '↾',
  Leftarrow: '⇐',
  nRightarrow: '⇏',
  upuparrows: '⇈',
  leftarrowtail: '↢',
  nwarrow: '↖',
  leftharpoondown: '↽',
  Rarr: '⇒',

  pm: '±',
  plusmn: '±',
  times: '×',
  ltimes: '⋉',
  rtimes: '⋊',
  div: '÷',

  aleph: 'ℵ',
  alef: 'ℵ',
  alefsym: 'ℵ',
  beth: 'ℶ',
  gimel: 'ℷ',
  daleth: 'ℸ',
  eth: 'ð',
  matheth: 'ð',

  ell: 'ℓ',
  wp: '℘',
  weierp: '℘',
  turnediota: '℩',
  Angstrom: 'Å',
  imath: 'ı',
  jmath: 'ȷ',
  textpilcrow: '¶',
  textborn: '*',
  textdied: '†',
  textlbrackdbl: '⟦',
  textrbrackdbl: '⟧',
  textguarani: '₲',


  mathhyphen: '‐',
  closure: '⁐',
  leftwavearrow: '↜',
  rightwavearrow: '↝',
  twoheaduparrow: '↟',
  twoheaddownarrow: '↡',
  mapsfrom: '↤',
  mapsup: '↥',
  mapsdown: '↧',
  downzigzagarrow: '↯',
  Ldsh: '↲',
  Rdsh: '↳',
  updownarrows: '⇅',
  Nwarrow: '⇖',
  Nearrow: '⇗',
  Searrow: '⇘',
  Swarrow: '⇙',
  leftsquigarrow: '⇜',
  barleftarrow: '⇤',
  rightarrowbar: '⇥',
  circleonrightarrow: '⇴',
  downuparrows: '⇵',
  rightthreearrows: '⇶',
  nvleftarrow: '⇷',
  nvrightarrow: '⇸',
  nvleftrightarrow: '⇹',
  nVleftarrow: '⇺',
  nVrightarrow: '⇻',
  nVleftrightarrow: '⇼',
  leftarrowtriangle: '⇽',
  rightarrowtriangle: '⇾',
  leftrightarrowtriangle: '⇿',
  smallin: '∊',
  nni: '∌',
  smallni: '∍',
  mathratio: '∶',
  Colon: '∷',
  dashcolon: '∹',
  dotsminusdots: '∺',
  kernelcontraction: '∻',
  nsime: '≄',
  sime: '≃',
  simneqq: '≆',
  napprox: '≉',
  approxident: '≋',
  backcong: '≌',
  circeq: '≗',
  arceq: '≘',
  wedgeq: '≙',
  veeeq: '≚',
  stareq: '≛',
  eqdef: '≝',
  measeq: '≞',
  questeq: '≟',
  nequiv: '≢',
  Equiv: '≣',
  nasymp: '≭',
  nlesssim: '≴',
  ngtrsim: '≵',
  nlessgtr: '≸',
  ngtrless: '≹',
  nsubset: '⊄',
  nsupset: '⊅',
  assert: '⊦',
  VDash: '⊫',
  prurel: '⊰',
  scurel: '⊱',
  equalparallel: '⋕',
  lessdot: '⋖',
  gtrdot: '⋗',
  eqless: '⋜',
  eqgtr: '⋝',
  npreccurlyeq: '⋠',
  nsucccurlyeq: '⋡',
  nsqsubseteq: '⋢',
  nsqsupseteq: '⋣',
  sqsubsetneq: '⋤',
  sqsupsetneq: '⋥',
  nvartriangleleft: '⋪',
  nvartriangleright: '⋫',
  adots: '⋰',
  disin: '⋲',
  varisins: '⋳',
  isins: '⋴',
  isindot: '⋵',
  varisinobar: '⋶',
  isinobar: '⋷',
  isinvb: '⋸',
  isinE: '⋹',
  nisd: '⋺',
  varnis: '⋻',
  nis: '⋼',
  varniobar: '⋽',
  niobar: '⋾',
  bagmember: '⋿',
  APLnotslash: '⌿',
  bsolhsub: '⟈',
  suphsol: '⟉',
  upin: '⟒',
  pullback: '⟓',
  pushout: '⟔',
  DashVDash: '⟚',
  dashVdash: '⟛',
  multimapinv: '⟜',
  vlongdash: '⟝',
  longdashv: '⟞',
  cirbot: '⟟',
  UUparrow: '⟰',
  DDownarrow: '⟱',
  acwgapcirclearrow: '⟲',
  cwgapcirclearrow: '⟳',
  rightarrowonoplus: '⟴',
  longmapsfrom: '⟻',
  Longmapsfrom: '⟽',
  Longmapsto: '⟾',
  longrightsquigarrow: '⟿',
  nvtwoheadrightarrow: '⤀',
  nVtwoheadrightarrow: '⤁',
  nvLeftarrow: '⤂',
  nvRightarrow: '⤃',
  nvLeftrightarrow: '⤄',
  twoheadmapsto: '⤅',
  Mapsfrom: '⤆',
  Mapsto: '⤇',
  downarrowbarred: '⤈',
  uparrowbarred: '⤉',
  Uuparrow: '⤊',
  Ddownarrow: '⤋',
  leftbkarrow: '⤌',
  rightbkarrow: '⤍',
  leftdbkarrow: '⤎',
  dbkarrow: '⤏',
  drbkarrow: '⤐',
  rightdotarrow: '⤑',
  baruparrow: '⤒',
  downarrowbar: '⤓',
  nvrightarrowtail: '⤔',
  nVrightarrowtail: '⤕',
  twoheadrightarrowtail: '⤖',
  nvtwoheadrightarrowtail: '⤗',
  nVtwoheadrightarrowtail: '⤘',
  lefttail: '⤙',
  righttail: '⤚',
  leftdbltail: '⤛',
  rightdbltail: '⤜',
  diamondleftarrow: '⤝',
  rightarrowdiamond: '⤞',
  diamondleftarrowbar: '⤟',
  barrightarrowdiamond: '⤠',
  nwsearrow: '⤡',
  neswarrow: '⤢',
  hknwarrow: '⤣',
  hknearrow: '⤤',
  hksearrow: '⤥',
  hkswarrow: '⤦',
  tona: '⤧',
  toea: '⤨',
  tosa: '⤩',
  towa: '⤪',
  rightcurvedarrow: '⤳',
  leftdowncurvedarrow: '⤶',
  rightdowncurvedarrow: '⤷',
  cwrightarcarrow: '⤸',
  acwleftarcarrow: '⤹',
  acwoverarcarrow: '⤺',
  acwunderarcarrow: '⤻',
  curvearrowrightminus: '⤼',
  curvearrowleftplus: '⤽',
  cwundercurvearrow: '⤾',
  ccwundercurvearrow: '⤿',
  acwcirclearrow: '⥀',
  cwcirclearrow: '⥁',
  rightarrowshortleftarrow: '⥂',
  leftarrowshortrightarrow: '⥃',
  shortrightarrowleftarrow: '⥄',
  rightarrowplus: '⥅',
  leftarrowplus: '⥆',
  rightarrowx: '⥇',
  leftrightarrowcircle: '⥈',
  twoheaduparrowcircle: '⥉',
  leftrightharpoonupdown: '⥊',
  leftrightharpoondownup: '⥋',
  updownharpoonrightleft: '⥌',
  updownharpoonleftright: '⥍',
  leftrightharpoonupup: '⥎',
  updownharpoonrightright: '⥏',
  leftrightharpoondowndown: '⥐',
  updownharpoonleftleft: '⥑',
  barleftharpoonup: '⥒',
  rightharpoonupbar: '⥓',
  barupharpoonright: '⥔',
  downharpoonrightbar: '⥕',
  barleftharpoondown: '⥖',
  rightharpoondownbar: '⥗',
  barupharpoonleft: '⥘',
  downharpoonleftbar: '⥙',
  leftharpoonupbar: '⥚',
  barrightharpoonup: '⥛',
  upharpoonrightbar: '⥜',
  bardownharpoonright: '⥝',
  leftharpoondownbar: '⥞',
  barrightharpoondown: '⥟',
  upharpoonleftbar: '⥠',
  bardownharpoonleft: '⥡',
  leftharpoonsupdown: '⥢',
  upharpoonsleftright: '⥣',
  rightharpoonsupdown: '⥤',
  downharpoonsleftright: '⥥',
  leftrightharpoonsup: '⥦',
  leftrightharpoonsdown: '⥧',
  rightleftharpoonsup: '⥨',
  rightleftharpoonsdown: '⥩',
  leftharpoonupdash: '⥪',
  dashleftharpoondown: '⥫',
  rightharpoonupdash: '⥬',
  dashrightharpoondown: '⥭',
  updownharpoonsleftright: '⥮',
  downupharpoonsleftright: '⥯',
  rightimply: '⥰',
  equalrightarrow: '⥱',
  similarrightarrow: '⥲',
  leftarrowsimilar: '⥳',
  rightarrowsimilar: '⥴',
  rightarrowapprox: '⥵',
  ltlarr: '⥶',
  leftarrowless: '⥷',
  gtrarr: '⥸',
  subrarr: '⥹',
  leftarrowsubset: '⥺',
  suplarr: '⥻',
  leftfishtail: '⥼',
  rightfishtail: '⥽',
  upfishtail: '⥾',
  downfishtail: '⥿',
  typecolon: '⦂',
  rtriltri: '⧎',
  ltrivb: '⧏',
  vbrtri: '⧐',
  lfbowtie: '⧑',
  rfbowtie: '⧒',
  fbowtie: '⧓',
  lftimes: '⧔',
  rftimes: '⧕',
  dualmap: '⧟',
  lrtriangleeq: '⧡',
  eparsl: '⧣',
  smeparsl: '⧤',
  eqvparsl: '⧥',
  gleichstark: '⧦',
  ruledelayed: '⧴',
  veeonwedge: '⩙',
  eqdot: '⩦',
  dotequiv: '⩧',
  equivVert: '⩨',
  equivVvert: '⩩',
  dotsim: '⩪',
  simrdots: '⩫',
  simminussim: '⩬',
  congdot: '⩭',
  asteq: '⩮',
  hatapprox: '⩯',
  approxeqq: '⩰',
  eqqsim: '⩳',
  eqeq: '⩵',
  eqeqeq: '⩶',
  ddotseq: '⩷',
  equivDD: '⩸',
  ltcir: '⩹',
  gtcir: '⩺',
  ltquest: '⩻',
  gtquest: '⩼',
  lesdot: '⩿',
  gesdot: '⪀',
  lesdoto: '⪁',
  gesdoto: '⪂',
  lesdotor: '⪃',
  gesdotol: '⪄',
  lsime: '⪍',
  gsime: '⪎',
  lsimg: '⪏',
  gsiml: '⪐',
  lgE: '⪑',
  glE: '⪒',
  lesges: '⪓',
  gesles: '⪔',
  elsdot: '⪗',
  egsdot: '⪘',
  eqqless: '⪙',
  eqqgtr: '⪚',
  eqqslantless: '⪛',
  eqqslantgtr: '⪜',
  simless: '⪝',
  simgtr: '⪞',
  simlE: '⪟',
  simgE: '⪠',
  Lt: '⪡',
  Gt: '⪢',
  partialmeetcontraction: '⪣',
  glj: '⪤',
  gla: '⪥',
  ltcc: '⪦',
  gtcc: '⪧',
  lescc: '⪨',
  gescc: '⪩',
  smt: '⪪',
  lat: '⪫',
  smte: '⪬',
  late: '⪭',
  bumpeqq: '⪮',
  precneq: '⪱',
  succneq: '⪲',
  preceqq: '⪳',
  succeqq: '⪴',
  Prec: '⪻',
  Succ: '⪼',
  subsetdot: '⪽',
  supsetdot: '⪾',
  subsetplus: '⪿',
  supsetplus: '⫀',
  submult: '⫁',
  supmult: '⫂',
  subedot: '⫃',
  supedot: '⫄',
  subsim: '⫇',
  supsim: '⫈',
  subsetapprox: '⫉',
  supsetapprox: '⫊',
  lsqhook: '⫍',
  rsqhook: '⫎',
  csub: '⫏',
  csup: '⫐',
  csube: '⫑',
  csupe: '⫒',
  subsup: '⫓',
  supsub: '⫔',
  subsub: '⫕',
  supsup: '⫖',
  suphsub: '⫗',
  supdsub: '⫘',
  forkv: '⫙',
  topfork: '⫚',
  mlcp: '⫛',
  forks: '⫝̸',
  forksnot: '⫝',
  shortlefttack: '⫞',
  shortdowntack: '⫟',
  shortuptack: '⫠',
  vDdash: '⫢',
  dashV: '⫣',
  Dashv: '⫤',
  DashV: '⫥',
  varVdash: '⫦',
  Barv: '⫧',
  vBar: '⫨',
  vBarv: '⫩',
  barV: '⫪',
  Vbar: '⫫',
  Not: '⫬',
  bNot: '⫭',
  revnmid: '⫮',
  cirmid: '⫯',
  midcir: '⫰',
  nhpar: '⫲',
  parsim: '⫳',
  lllnest: '⫷',
  gggnest: '⫸',
  leqqslant: '⫹',
  geqqslant: '⫺',
  circleonleftarrow: '⬰',
  leftthreearrows: '⬱',
  leftarrowonoplus: '⬲',
  longleftsquigarrow: '⬳',
  nvtwoheadleftarrow: '⬴',
  nVtwoheadleftarrow: '⬵',
  twoheadmapsfrom: '⬶',
  twoheadleftdbkarrow: '⬷',
  leftdotarrow: '⬸',
  nvleftarrowtail: '⬹',
  nVleftarrowtail: '⬺',
  twoheadleftarrowtail: '⬻',
  nvtwoheadleftarrowtail: '⬼',
  nVtwoheadleftarrowtail: '⬽',
  leftarrowx: '⬾',
  leftcurvedarrow: '⬿',
  equalleftarrow: '⭀',
  bsimilarleftarrow: '⭁',
  leftarrowbackapprox: '⭂',
  rightarrowgtr: '⭃',
  rightarrowsupset: '⭄',
  LLeftarrow: '⭅',
  RRightarrow: '⭆',
  bsimilarrightarrow: '⭇',
  rightarrowbackapprox: '⭈',
  similarleftarrow: '⭉',
  leftarrowapprox: '⭊',
  leftarrowbsimilar: '⭋',
  rightarrowbsimilar: '⭌',


  /* Spacing */
  ',': ' ',
  ':': ' ',
  ';': ' '.repeat(2),
  '!': '', // stub
  quad: ' '.repeat(4),
  qquad: ' '.repeat(6),
  thinspace: ' ',
  medspace: ' ',
  thickspace: ' '.repeat(2),
  enspace: ' '.repeat(2),
  negthickspace: '', // stub
  negthinspace: '', // stub
  negmedspace: '', // stub



  '(': '(',
  ')': ')',
  '[': '[',
  ']': ']',
  '{': '{',
  '}': '}',
  '<': '⟨',
  '>': '⟩',
  '%': '%',
  '\\': '\n',
  'newline': '\n',

  Game: '⅁',
  because: '∵',
  suchthat: '∴',
};


const FixedInfixes = [
  'plus', 'minus',
  'cdot', 'gtrdot', 'cdotp',
  'intercal', 'centerdot', 'land',
  'rhd', 'circ', 'leftthreetimes',
  'rightthreetimes', 'amalg', 'circledast',
  'ldotp', 'rtimes', 'And',
  'circledcirc', 'lor', 'setminus',
  'ast', 'circleddash', 'lessdot',
  'smallsetminus', 'barwedge', 'Cup',
  'lhd', 'sqcap', 'bigcirc',
  'cup', 'ltimes', 'sqcup',
  'bmod', 'curlyvee', 'mod',
  'times', 'boxdot', 'curlywedge',
  'mp', 'unlhd', 'boxminus',
  'div', 'odot', 'unrhd',
  'boxplus', 'divideontimes', 'ominus',
  'uplus', 'boxtimes', 'dotplus',
  'oplus', 'vee', 'bullet',
  'doublebarwedge', 'otimes', 'veebar',
  'Cap', 'doublecap', 'oslash',
  'wedge', 'cap', 'doublecup',
  'pm', 'plusmn', 'wr'
];
export { FixedInfixes };

const operatorNames = [
  'arcsin', 'arccos', 'arctan', 'arctg',
  'arcctg', 'arg', 'ch', 'cos',
  'det', 'gcd', 'inf', 'cosec',
  'cosh', 'cot', 'cotg', 'coth',
  'csc', 'ctg', 'cth', 'lim',
  'max', 'deg', 'dim', 'exp',
  'hom', 'ker', 'lg', 'ln',
  'log', 'min', 'plim', 'Pr',
  'sup', 'sec', 'sin', 'sinh',
  'sh', 'tan', 'tanh', 'tg',
  'th'
];
operatorNames.forEach(x => stableFixed[x] = x);

const greeks = [
  'Alpha', 'Beta', 'Gamma', 'Delta',
  'Epsilon', 'Zeta', 'Eta', 'Theta',
  'Iota', 'Kappa', 'Lambda', 'Mu',
  'Nu', 'Xi', 'Omicron', 'Pi',
  'Rho', 'Sigma', 'Tau', 'Upsilon',
  'Phi', 'Chi', 'Psi', 'Omega',
  'alpha', 'beta', 'gamma', 'delta',
  'epsilon', 'zeta', 'eta', 'theta',
  'iota', 'kappa', 'lambda', 'mu',
  'nu', 'xi', 'omicron', 'pi',
  'rho', 'sigma', 'tau', 'upsilon',
  'phi', 'chi', 'psi', 'omega'
]
greeks.forEach((x, i) => stableFixed[x] = Unicode.greeks[i]);
stableFixed.epsilon = 'ϵ';
stableFixed.phi = 'ϕ';

export const stableValue = (key: string): string => stableFixed[key] as string;

// fixed symbol as supscripts
Unicode.supscripts[stableValue("times")] = Unicode.supscripts.x;

// fixed symbol as subscripts
Unicode.subscripts[stableValue("in")] = stableValue("smallin");
Unicode.subscripts[stableValue("ni")] = stableValue("smallni");

// Gothic
// oxlint-disable-next-line no-unused-vars
const gothics = ['ahsa', 'bairkan', 'giba', 'dags', 'aihvus'];

export default stableFixed;
